### ISSUE TITLE
Bug: some messages with images are represented only as "Image was sent: undefined"

### ISSUE THREAD

**Issue by Rud356** [innereq/mx-puppet-vk#16]
I've been using:
mx-puppet-vk v0.51.0
node.js v14.17.1
npm v6.14.13

Also it was on user token, not group one.
Some messages come fine from one album of images, but others don't, even if they're all in jpg format

**Comment by inexcode** [comment]
Do you have any logs? There should be the source code of incoming message on DEBUG log level, that would be very helpful.

User tokens are experimental, and as I have no VK account, I can only debug it with someone else's log.

**Comment by inexcode** [comment]
I can see you are already fixing this. Feel free to send a PR after you are done.

**Comment by Rud356** [comment]
Okay, I think I've fixed it and trouble was in a way image with max resolution was looked up. It was looking for exact images type represented as character, while I decided to work with only images resolutions sum of height and width to be as big as possible, which seems to be working right now. Gonna clean up a code and send PR soon.
