### ISSUE TITLE
Post info about receiving unknown message types into Matrix room

### ISSUE THREAD

**Issue by MurzNN** [innereq/mx-puppet-vk#9]
When bridge receive the message, which it can't render properly, will be good to inform user that it received something, even if we can't render it. Send a simple message with text like "Received unknown event type (id = 123)" and the user will can go to native client (VK web interface) to view it.
Now bridge skips those messages, so user even didn't get informed that he received something unrenderable.

**Comment by inexcode** [comment]
As most of these cases are because of unknown attachments, should be fixed now.
Reopen if messages are still lost.
